import assert from 'node:assert/strict';
import { makeJob, validateJob, jobHash, validateApi, extractValues, validateResult, apiEnvironment } from '../jobs.mjs';
const base = makeJob();
const api = { server: 'api.kucoin.com', path: '/api/v1/market/orderbook/level1?symbol=BTC-USDT', method: 'GET', extract: [{ name:'price', pointer:'/data/price', type:'decimal' }, { name:'timestamp', pointer:'/data/time', type:'number' }] };
const job = validateJob({ ...base, version:2, api });
assert.equal(apiEnvironment(job).API_GENERIC, '1');
assert.deepEqual({...extractValues({data:{price:'100.123',time:123}},api)}, {price:'100.123', timestamp:123});
assert.notEqual(jobHash(job), jobHash({...job,api:{...api,path:'/different'}}));
assert.notEqual(jobHash(job), jobHash({...job,api:{...api,extract:[{name:'value',pointer:'/data/price',type:'string'}]}}));
for (const server of ['127.0.0.1','localhost','api.local','api.example','API.KUCOIN.COM','evil.com:443','user@evil.com','evil.com\r\nHost: x']) assert.throws(() => validateApi({...api,server}));
for (const path of ['//evil.com/','/\r\nHost: evil','/x#fragment','/x\\y','/x%xx']) assert.throws(() => validateApi({...api,path}));
assert.throws(() => validateApi({...api,method:'POST'}));
assert.throws(() => validateApi({...api,headers:{Authorization:'secret'}}));
assert.throws(() => extractValues({data:{}}, api), /Missing/);
assert.throws(() => extractValues({data:{price:1,time:1}}, api), /type/);
assert.throws(() => extractValues({data:{price:'1',time:Number.MAX_SAFE_INTEGER+1}}, api), /type/);
assert.throws(() => extractValues({}, {...api,extract:[{name:'value',pointer:'/toString',type:'string'}]}), /Missing/);
const result = {verified:true,server:api.server,path:api.path,method:'GET',response:{data:{price:'1.25',time:123}},jobChallenge:jobHash(job),tlsSessionTimeSeconds:Math.floor(Date.now()/1000),requestHex:'00',responseHex:'00'};
validateResult(result,job,Date.now(),true);
assert.throws(() => validateResult({...result,path:'/different'},job), /Unexpected/);
assert.throws(() => validateResult({...result,method:'POST'},job), /Unexpected/);
console.log('PASS API jobs: canonical v2 binding, strict public GET schema, JSON pointers/types, extraction failure, endpoint mismatch, v1 compatibility');
